# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Guerra\Desktop\Scripts\Python\tallerDesarrollo\Proyecto-Taller-Desarrollo-de-Aplicaciones\Assets\anotherUntitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_ingresar.setGeometry(QtCore.QRect(210, 200, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.boton_ingresar.setFont(font)
        self.boton_ingresar.setObjectName("boton_ingresar")
        self.rut = QtWidgets.QLabel(self.centralwidget)
        self.rut.setGeometry(QtCore.QRect(20, 40, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rut.setFont(font)
        self.rut.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rut.setAlignment(QtCore.Qt.AlignCenter)
        self.rut.setObjectName("rut")
        self.clave = QtWidgets.QLabel(self.centralwidget)
        self.clave.setGeometry(QtCore.QRect(20, 120, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clave.setFont(font)
        self.clave.setAlignment(QtCore.Qt.AlignCenter)
        self.clave.setObjectName("clave")
        self.clave_placeholder = QtWidgets.QLineEdit(self.centralwidget)
        self.clave_placeholder.setGeometry(QtCore.QRect(170, 120, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.clave_placeholder.setFont(font)
        self.clave_placeholder.setText("")
        self.clave_placeholder.setEchoMode(QtWidgets.QLineEdit.Password)
        self.clave_placeholder.setAlignment(QtCore.Qt.AlignCenter)
        self.clave_placeholder.setObjectName("clave_placeholder")
        self.boton_ingresar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_ingresar_2.setGeometry(QtCore.QRect(220, 290, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.boton_ingresar_2.setFont(font)
        self.boton_ingresar_2.setObjectName("boton_ingresar_2")
        self.clave_placeholder_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.clave_placeholder_2.setGeometry(QtCore.QRect(170, 30, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.clave_placeholder_2.setFont(font)
        self.clave_placeholder_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.clave_placeholder_2.setAlignment(QtCore.Qt.AlignCenter)
        self.clave_placeholder_2.setObjectName("clave_placeholder_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_ingresar.setText(_translate("MainWindow", "Ingresar"))
        self.rut.setText(_translate("MainWindow", "RUT"))
        self.clave.setText(_translate("MainWindow", "Contraseña"))
        self.clave_placeholder.setPlaceholderText(_translate("MainWindow", "Password"))
        self.boton_ingresar_2.setText(_translate("MainWindow", "Olvide mi contraseña"))
        self.clave_placeholder_2.setPlaceholderText(_translate("MainWindow", "20831606-0"))
