# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Guerra\desktop\scripts\repos\tda-project\LoginView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(948, 832)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_rut = QtWidgets.QLineEdit(self.centralwidget)
        self.input_rut.setGeometry(QtCore.QRect(250, 220, 461, 81))
        self.input_rut.setObjectName("input_rut")
        self.input_password = QtWidgets.QLineEdit(self.centralwidget)
        self.input_password.setGeometry(QtCore.QRect(250, 340, 461, 81))
        self.input_password.setObjectName("input_password")
        self.b_login = QtWidgets.QPushButton(self.centralwidget)
        self.b_login.setGeometry(QtCore.QRect(380, 450, 191, 81))
        self.b_login.setObjectName("b_login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 60, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 560, 191, 71))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_rut.setPlaceholderText(_translate("MainWindow", "Rut"))
        self.input_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.b_login.setText(_translate("MainWindow", "Iniciar Sesion"))
        self.label.setText(_translate("MainWindow", "El correo de yury"))
        self.pushButton.setText(_translate("MainWindow", "Olvide mi contraseña"))
